---
title: "Data Types and Data Structures in R"
author: "Programming for Analytics"
date: "17/09/2021"
output: html_document
---
## Assignment Authors
* Aditi Singh
* Arsh Kumbhat
* Jainil Shah
* Vibha Rao
* Revendranath T

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Exercise 1

Find the class and type of 'x' in the following cases:- 

1. x=22   // *Modify the code to create or declare an integer value.*  
2. y= 2    
   z=3  
   x=y>z   
3. x = 2i  
4. x="20-09-2021"  

   
### Exercise 2

1. Find the output when 1+2i is converted to character type  
2. Find output when "ProgrammingForAnalytics" is converted to numeric type
3. Given: x<-0:5, write code to output:  
   [1] FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  (and)  
   [1] "0" "1" "2" "3" "4" "5" 
4. Given: x<-c("a","b","c")  
   Do all possible coercions to output [1] NA NA NA  
       
       

### Exercise 3

Fill the table with your understanding of Data Structures (Atomic vector, List, Dataframe, Array, Matrix)

|                |   Linear |   2 Dimensional   | N Dimensional |
|----------------|----------|-------------------|---------------|
|**Homogenous**  |          |                   |               |
|**Heterogenous**|          |                   |               |  


### Exercise 4

Create a vector with a sequence of descending numbers from 20 to 0 in steps of 2. 

(i) Write code to access all except the 2nd to 5th elements.
(ii) Write code to access all numbers greater than 10 excluding the one at 2nd index.
(iii) Write code to change values of all elements less than 10 to 0.
    
### Exercise 5   
    
Create a matrix with 2 columns and 4 rows by passing a vector having 4 repetitions of 1 and 2 (i.e., 1,2,1,2,... use rep() command). Arrange these elements in a row-wise manner.

(i) Write code to access the 2nd column of this matrix.  
(ii) Name the columns: "c1", "c2". Name the rows: "r1", "r2", "r3", "r4".  
(iii) Write code to access the 2nd row using its row name.  
(iv) Delete the first row

### Exercise 6

(i) Create a vector "V" which contains 10 random integer values between -100 and +100. (hint:)
(ii) Create a two-dimensional 5×5 array "A" comprised of sequence of even integers greater than 25.
(iii) Create a list "S" containing sequence of 20 capital letters, starting with ‘C’.  

Create a list named "l" containing all the previously created objects. Name them "my_vector", "my_array"  and "my_list" respectively.  

Without running any R command, answer the following questions pertaining to the exercise :-

1. How many elements are there in the list?
2. what is the result of l[[3]]?
3. How would you access random-th letter in the list element "my_list"?
4. If you convert list l to a vector, what will be the type of it’s elements?
5. Can this list be converted to an array? What will be the data type of elements in array?
6. How would you add a new element to this list?


       
### Exercise 7

Write a program to create a Data Frame by passing vectors for name (character), age (integer) and vaccinated (logical). 

1. Print the number of rows using dim().
2. Write code to change the age column into complex data type.
3. Use "as" function to check if dataframes can be coerced into other data types or data structures.

### Exercise 8

Debug the following and run the correct code  
1. num = c(1, 2, 3, 4, 5)  
   name = c("one", "two", "four", "five")  
   df = data.frame(num,name)  
   print(df)  
2. x = c(1, "BITS", 5, 7.2, True, 1+i)  
   print(X)


  


## Resources
1. https://www.geeksforgeeks.org/r-data-types/
2. https://technicaljockey.com/r-programming-training/coercion-in-r/  
3. https://www.w3resource.com/r-programming-exercises/
4. https://rspatial.org/intr/3-basic-data-structures.html

