---
title: "Assignment 3"
author: "PfA Teaching Team"
date: "10/18/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Assignment 3: Data Wrangling

ABC Lendtech is an early stage startup with an idea to provide a loan amount of upto INR 5,00,000 to students.As they are early stage start-up, they do not have history. The leadership team of ABC Lendtech purchases data from a third party vendor related to past students loan data. The CEO of ABC Lendtech hires you as a Chief Data Scientist, and expects you to provide data driven strategy for the company. Analyse the dataset shared at this link, and pitch your data driven strategy to the CEO of ABC Lendtech based on your observations from data cleaning, summary of descriptive statistics, and visualisation

### Hints:
* Clean the data
* Ensure consistency in values
* Check if some values in columns need to be converted into categorical variables, and make necessary changes
* The proportion of loan amount paid is empty, calculate it against each loan account correctly (Maximum number of installments are 48)
* Handle missing values and provide reason and details on how you handled them
* Summarise the count of good loan and bad loan, against the purpose of the loan.
* Provide summary of potential defaulters from the descriptive statistics
* Visualise the data to see if there are patterns and make observations
* Provide a one page summary on your observations